import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

// Fontawesome / SVG Core API
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { library } from '@fortawesome/fontawesome-svg-core';

// Import Base / Solid Icons
import {
  faAngleDown,
  faAt,
  faAward,
  faBroom,
  faBug,
  faChartBar,
  faChartLine,
  faChartPie,
  faCircle,
  faClock,
  faChess,
  faCloudDownloadAlt,
  faCode,
  faCookie,
  faCookieBite,
  faCrown,
  faCubes,
  faDiceD20,
  faDna,
  faDownload,
  faEnvelope,
  faEllipsisV,
  faFile,
  faFileAlt,
  faFileArchive,
  faFileCode,
  faFileDownload,
  faFileExcel,
  faFileExport,
  faFileImage,
  faFileImport,
  faFilePdf,
  faFileWord,
  faFingerprint,
  faFlask,
  faGraduationCap,
  faHome,
  faIdBadge,
  faIdCard,
  faInfoCircle,
  faLightbulb,
  faLink,
  faMapMarked,
  faMapMarkedAlt,
  faMapMarkerAlt,
  faMapPin,
  faMeteor,
  faMicrochip,
  faPencilRuler,
  faPoo,
  faShareAltSquare,
  faSquare,
  faSquareFull,
  faSwatchbook,
  faTachometerAlt,
  faTerminal,
  faToolbox,
  faTools,
  faTrafficLight,
  faUser,
  faUserAstronaut

} from '@fortawesome/free-solid-svg-icons';

// Import Brand Icons
import {
  faAngular,
  faApple,
  faAws,
  faChrome,
  faCss3,
  faCss3Alt,
  faDocker,
  faEmber,
  faExpeditedssl,
  faFacebook,
  faFirefox,
  faGithubSquare,
  faGithubAlt,
  faGitSquare,
  faGooglePlus,
  faGooglePlusSquare,
  faGrunt,
  faGulp,
  faHtml5,
  faInstagram,
  faJsSquare,
  faLinkedin,
  faNode,
  faNodeJs,
  faNpm,
  faReact,
  faSass,
  faStackExchange,
  faStackOverflow,
  faTwitter,
  faTwitterSquare,
  faVuejs,
  faWindows

} from '@fortawesome/free-brands-svg-icons';

@NgModule({
  imports: [
    CommonModule,
    FontAwesomeModule
  ],
  declarations: [ ],
  exports: [
    FontAwesomeModule
  ]
})

export class IconsModule {

    constructor () {
        // Base / Solid Icons
        // Add icons to `library` Object to make them accessible
        // Sanity Check:: Icons are listed in alphabetical order
        library.add(
          faAngleDown,
          faAt,
          faAward,
          faBroom,
          faBug,
          faChartBar,
          faChartLine,
          faChartPie,
          faCircle,
          faClock,
          faChess,
          faCloudDownloadAlt,
          faCode,
          faCookie,
          faCookieBite,
          faCrown,
          faCubes,
          faDiceD20,
          faDna,
          faDownload,
          faEnvelope,
          faEllipsisV,
          faFile,
          faFileAlt,
          faFileArchive,
          faFileCode,
          faFileDownload,
          faFileExcel,
          faFileExport,
          faFileImage,
          faFileImport,
          faFilePdf,
          faFileWord,
          faFingerprint,
          faFlask,
          faGraduationCap,
          faHome,
          faIdBadge,
          faIdCard,
          faInfoCircle,
          faLightbulb,
          faLink,
          faMapMarked,
          faMapMarkedAlt,
          faMapMarkerAlt,
          faMapPin,
          faMeteor,
          faMicrochip,
          faPencilRuler,
          faPoo,
          faShareAltSquare,
          faSquare,
          faSquareFull,
          faSwatchbook,
          faTachometerAlt,
          faTerminal,
          faTools,
          faToolbox,
          faTrafficLight,
          faUser,
          faUserAstronaut,

          // Brand Icons /////////////////////////
          faAngular,
          faApple,
          faAws,
          faChrome,
          faCss3,
          faCss3Alt,
          faDocker,
          faEmber,
          faExpeditedssl,
          faFacebook,
          faFirefox,
          faGithubSquare,
          faGithubAlt,
          faGitSquare,
          faGooglePlus,
          faGooglePlusSquare,
          faGrunt,
          faGulp,
          faHtml5,
          faInstagram,
          faJsSquare,
          faLinkedin,
          faNode,
          faNodeJs,
          faNpm,
          faReact,
          faSass,
          faStackExchange,
          faStackOverflow,
          faTwitter,
          faTwitterSquare,
          faVuejs,
          faWindows
        );
    }
}
